### PR TITLE
Don't allow leading zeroes for quantities

### LINKED ISSUE #1392: eth_getFilterLogs not working on hardhat due to hex prefix
# eth_getFilterLogs not working on hardhat due to hex prefix

## Steps To Reproduce
Run a hardhat server with a smart contract, execute a event flowable call against it.

### Expected behavior
It should work.

### Actual behavior
The filter call fails.
The sequence of calls to the endpoint is:
```
call:
{"jsonrpc":"2.0","method":"eth_newFilter","params":[{"topics":["0x22[....]"],"fromBlock":"0x1","toBlock":"0x174876e800","address":["0x5F[...]"]}],"id":1}
response: 
{"jsonrpc":"2.0","id":1,"result":"0x5"}

next call web3j -> api:
{"jsonrpc":"2.0","method":"eth_getFilterLogs","params":["0x05"],"id":2}
response:
{"jsonrpc":"2.0","id":2,"error":{"code":-32602,"message":"Errors encountered in param 0: Invalid value \"0x05\" supplied to : QUANTITY"}}
```

I checked with curl, and when the call would be `{"jsonrpc":"2.0","method":"eth_getFilterLogs","params":["0x5"],"id":2}`, i.e., without the leading zero in the hex code of the params, then it works.

The [API spec](https://ethereum.org/nl/developers/docs/apis/json-rpc/#hex-value-encoding) says "WRONG: 0x0400 (no leading zeroes allowed)", but web3j is using `Numeric::toHexStringWithPrefixSafe` which does add leading zeroes.
My particular problem comes from `JsonRpc2_0Web3j.java` line 524 where the `eth_getFilterLogs` request is built (and it uses that same method for a couple of other calls as well, which should probably also be changed?).

## Environment
- Web3j version 4.8.4
- JVM on Linux

### LINKED ISSUE #1631: Shouldn't prefix quantities according to JSON-RPC spec
https://github.com/web3j/web3j/blob/49fe2c4e2d9d325ec465879736d6c384f41a4115/core/src/main/java/org/web3j/protocol/core/JsonRpc2_0Web3j.java#L525

I'm using web3j to communicate with a Hardhat Node and getting an error with 'eth_getFilterLogs' because Web3j is formatting hex numbers with a leading 0.

According to the spec, numbers coming over JSON-RPC shouldn't have leading 0s.

https://eth.wiki/json-rpc/API

### LINKED ISSUE #1665: eth_getFilterLogs error
# _Bug_title_
method “eth_getFilterLogs” use a wrong params when filtereid less than 0x10

## Steps To Reproduce
This is my filter code.
```java
EthFilter filter = new EthFilter(
                DefaultBlockParameterName.EARLIEST,
                DefaultBlockParameterName.LATEST,
                contractAddress);
        filter.addSingleTopic(EventEncoder.encode(VotingContract.RETURNVOTEID_EVENT));
        web3j.ethLogFlowable(filter)
                .subscribe(log -> {
                    logger.info("hash:"+log.getTransactionHash()+";"+"data:"+log.getData());
                }, error -> {
                    error.printStackTrace();
                });
```

### Expected behavior
nothing output

### Actual behavior
```java
java.lang.NullPointerException
	at org.web3j.protocol.core.filters.LogFilter.process(LogFilter.java:46)
	at org.web3j.protocol.core.filters.Filter.getInitialFilterLogs(Filter.java:119)
	at org.web3j.protocol.core.filters.Filter.run(Filter.java:69)
	at org.web3j.protocol.rx.JsonRpc2_0Rx.run(JsonRpc2_0Rx.java:89)
	at org.web3j.protocol.rx.JsonRpc2_0Rx.lambda$ethLogFlowable$2(JsonRpc2_0Rx.java:79)
	at io.reactivex.internal.operators.flowable.FlowableCreate.subscribeActual(FlowableCreate.java:71)
	at io.reactivex.Flowable.subscribe(Flowable.java:14935)
	at io.reactivex.Flowable.subscribe(Flowable.java:14872)
	at io.reactivex.Flowable.subscribe(Flowable.java:14791)
	at cn.edu.zjucst.listener.ContractListener.newVote(ContractListener.java:49)
	at cn.edu.zjucst.listener.ContractListener.run(ContractListener.java:39)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:795)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:785)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:333)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1311)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1300)
	at cn.edu.zjucst.AppApplication.main(AppApplication.java:10)

```

## Environment
- Web3j version 4.8.7
- Java or Android version 1.8
- Operating System win10

## Additional context
- Logs
```
--> POST http://***.**.**.***:8545/

Content-Type: application/json; charset=utf-8

Content-Length: 241

{"jsonrpc":"2.0","method":"eth_newFilter","params":[{"topics":["0x4ad1269e844851cb096cb1288c24de3241625bc222823f047d80d388d31fe007"],"fromBlock":"earliest","toBlock":"latest","address":["0x3ad438090d6ca3c26f2e4c4c2e7833066b87e709"]}],"id":0}

--> END POST (241-byte body)

<-- 200 http://***.**.**.***:8545/ (159ms)

Content-Type: application/json

Content-Length: 39

{"id":0,"jsonrpc":"2.0","result":"0x1"}

<-- END HTTP (39-byte body)



--> POST http://***.**.**.***:8545/

Content-Type: application/json; charset=utf-8

Content-Length: 71

{"jsonrpc":"2.0","method":"eth_getFilterLogs","params":["0x01"],"id":1}

--> END POST (71-byte body)

<-- 200 http://***.**.**.***:8545/ (16ms)

Content-Type: application/json

Content-Length: 1051

{"id":1,"jsonrpc":"2.0","error":{"message":"filter not found","stack":"Error: filter not found\n    at EthereumApi.eth_getFilterLogs ......,"code":-32700}}

<-- END HTTP (1051-byte body)
```

modify request body `{"jsonrpc":"2.0","method":"eth_getFilterLogs","params":["0x01"],"id":1}` to `{"jsonrpc":"2.0","method":"eth_getFilterLogs","params":["0x1"],"id":1}` is working. 
I think the filterid in the'params' has a prefix 0 when filterid less than 0x10 causes the error.

When I repeat method 'eth_newFilter' until filterid equals 0x10, my code works.

### PR DESCRIPTION
**Pull request by Xilis**
### What does this PR do?
- parameters for the quantities in `ethUninstallFilter`, `ethGetFilterChanges` and `ethGetFilterLogs` calls are no longer zero padded
- the `isValidHexQuantity` validator is updated to match the specification
- test cases that are currently validating incorrect behavior are corrected

### Where should the reviewer start?
Start by observing that the changes being done were already planned for (the deleted comments), the issues were observed multiple times and some fixes were already proposed.

There are not many changes, so check the source code changes first and the updated tests should make it clear what is different.

### Why is it needed?
Currently, some quantities and parameters are zero padded (not in the most compact representation). Currently 1 is specified as 0x01 instead of 0x1. This is not compliant with the specification, quoted from [here](https://eth.wiki/json-rpc/API):

> HEX value encoding
> At present there are two key datatypes that are passed over JSON: unformatted byte arrays and quantities. Both are passed with a hex encoding, however with different requirements to formatting:
> 
> When encoding QUANTITIES (integers, numbers): encode as hex, prefix with “0x”, the most compact representation (slight exception: zero should be represented as “0x0”). Examples:
> 
> 0x41 (65 in decimal)
> 0x400 (1024 in decimal)
> WRONG: 0x (should always have at least one digit - zero is “0x0”)
> WRONG: 0x0400 (no leading zeroes allowed)
> WRONG: ff (must be prefixed 0x)
> When encoding UNFORMATTED DATA (byte arrays, account addresses, hashes, bytecode arrays): encode as hex, prefix with “0x”, two hex digits per byte. Examples:
> 
> 0x41 (size 1, “A”)
> 0x004200 (size 3, “\0B\0”)
> 0x (size 0, “”)
> WRONG: 0xf0f0f (must be even number of digits)
> WRONG: 004200 (must be prefixed 0x)

There are multiple open issues and PRs already documenting instances of issues, some of them linked below. 
Fixes #1392, fixes #1631, fixes #1665, duplicates #1580

### CODE REVIEW

**Review by gtebrean — APPROVED** [review]

File: core/src/main/java/org/web3j/protocol/core/JsonRpc2_0Web3j.java [hunk 1]
```diff
@@ -543,7 +543,7 @@ public Request<?, EthLog> ethGetFilterChanges(BigInteger filterId) {
     public Request<?, EthLog> ethGetFilterLogs(BigInteger filterId) {
         return new Request<>(
                 "eth_getFilterLogs",
-                Arrays.asList(Numeric.toHexStringWithPrefixSafe(filterId)),
+                Arrays.asList(Numeric.toHexStringWithPrefix(filterId)),
                 web3jService,
```
Comment (andrii-kl) [inline core/src/main/java/org/web3j/protocol/core/JsonRpc2_0Web3j.java:547]: Three methods are still using toHexStringWithPrefix
shhUninstallFilter, shhGetMessages, shhGetFilterChanges
Let's do it for all of them.

**Review by andrii-kl — COMMENTED** [review]
Let's mark method toHexStringWithPrefixSafe as a Deprecated. (Add description)

**Review by andrii-kl — APPROVED** [review]
