### PR TITLE
718: Added support for CLEARTEXT communication.

### LINKED ISSUE #770: CLEARTEXT communication not enabled for client
Hello,
Web3j web3j = Web3j.build(new HttpService("http://localhost:8545"));  
Exception:
CLEARTEXT communication not enabled for client

### PR DESCRIPTION
**Pull request by snazha-blkio**
### What does this PR do?
Adds support for http CLEARTEXT communication

### Where should the reviewer start?
HttpService.java

### Why is it needed?
Fixes #770

### CODE REVIEW

File: core/src/main/java/org/web3j/protocol/http/HttpService.java [hunk 1]
```diff
@@ -61,6 +65,11 @@
     private static final ConnectionSpec INFURA_CIPHER_SUITE_SPEC = new ConnectionSpec
             .Builder(ConnectionSpec.MODERN_TLS).cipherSuites(INFURA_CIPHER_SUITES).build();
 
+    /**
+     * The list of {@link ConnectionSpec} instances used by the connection.
+     */
+    private static final List<ConnectionSpec> CONNECTION_SPEC_LIST = Arrays.asList(INFURA_CIPHER_SUITE_SPEC, CLEARTEXT);
```
Comment (iikirilov) [inline core/src/main/java/org/web3j/protocol/http/HttpService.java]: Line should be less than 100 chars

File: core/src/main/java/org/web3j/protocol/http/HttpService.java [hunk 2]
```diff
@@ -112,8 +121,7 @@ public HttpService() {
     }
 
     private static OkHttpClient createOkHttpClient() {
-        OkHttpClient.Builder builder = new OkHttpClient.Builder()
-                .connectionSpecs(Collections.singletonList(INFURA_CIPHER_SUITE_SPEC));
+        OkHttpClient.Builder builder = new OkHttpClient.Builder().connectionSpecs(CONNECTION_SPEC_LIST);
```
Comment (iikirilov) [inline core/src/main/java/org/web3j/protocol/http/HttpService.java]: Line should be less than 100 chars

File: core/src/main/java/org/web3j/protocol/http/HttpService.java (hunk 1 above)
Comment (snazha-blkio) [reply core/src/main/java/org/web3j/protocol/http/HttpService.java]: Good spot, I thought I bumped it up to 120 chars in the 3.6 release. I'll change this line to make it 100.
